metadata.format.version = "1.1"

[versions]

# API
adventure = "4.11.0"
reflections = "0.10.2"

# Platforms
paper = "1.19.2-R0.1-SNAPSHOT"
velocity = "3.1.2-SNAPSHOT"

# Extras
worldguard = "7.0.8-SNAPSHOT"

[libraries]

# API
adventure = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
reflections = { group = "org.reflections", name = "reflections", version.ref = "reflections" }

# Platforms
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }

# Extras
worldguard = { group = "com.sk89q.worldguard", name = "worldguard-bukkit", version.ref = "worldguard" }